spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true